spring:
  datasource:
    url: jdbc:postgresql://120.79.62.203:5432/note
    username: zhanghang
    password: Zh@19970322
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  servlet:
    multipart:
      max-file-size: 20MB
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      use-registered-suffix-pattern: true
    date-format:  yyyy-MM-dd HH:mm:ss
config: config