spring:
  servlet:
    multipart:
      max-file-size: 20MB
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      use-registered-suffix-pattern: true
    date-format:  yyyy-MM-dd HH:mm:ss
